require("alucherdi.packer")
require("alucherdi.keymap")
require("alucherdi.autocmds")
require("alucherdi.set")
require("alucherdi.bindings")

require("alucherdi.plugconfs.treesitter")
require("alucherdi.plugconfs.lsp")
require("alucherdi.plugconfs.compe")
require("alucherdi.plugconfs.telescope")
require("alucherdi.plugconfs.blankline")
require("alucherdi.plugconfs.nvimtree")
require("alucherdi.plugconfs.harpoon")
require("alucherdi.plugconfs.gitsigns")

require("alucherdi.statusline")
require("alucherdi.colorscheme")
